Yi kai
SHINE-six/HireSight pull request #10
Opened 2024-04-15 14:11 UTC by yikai03

Added resumeRanking.py as model origin. Changes made in server.py. Provided a unit testing for resume ranking.py

2024-04-16 13:00 UTC, SHINE-six commented on backend/server.py
> +    for category in data:
need make amendment to fit with the new data structure

2024-04-16 13:00 UTC, SHINE-six commented on backend/server.py
>      filePath = "resume/resume_ranking.json"
bring up during meeting

2024-04-16 14:33 UTC, SHINE-six commented on backend/server.py
def resumeParseBinary(resume):

2024-04-16 14:51 UTC, SHINE-six commented on backend/server.py
> +    for category in data:
uploadResume(resume, jobDetail :{jobposition, jobDesc, jobSkill}, email, uniqueResumeID)

toStoreJson = {
  "filename": "",
  "email": email,
  "uniqueResumeId": uniqueResumeID,
  "jobPostitionApply": jobPostitionApply,
  "AiDetection": "",
  "plagiarism": "",
  "suitability": "",
  "stage": "Ai detection", // suitability
  "pdfData": {}
}
parsedBinaryPDF = resumeParseBinary(resume):
toStoreJson['filename'] = parsedBinaryPDF['filename']
toStoreJson['pdfData'] = parsedBinaryPDF['pdfData']

//missing model
parsedPdfToText

toStoreJson['suitability'] = resumeSuitability.main()
toStoreJson['AiDetection'] = AiDetection.main(parsedPdfToText)['ai_similarity']
toStoreJson['plagiarism'] = plagiarism.main(parsedPdfToText)['resuklt']

2024-04-16 15:28 UTC, SHINE-six requested changes

2024-04-16 15:28 UTC, SHINE-six commented on backend/server.py
> +    for category in data:
print(mongoDB.postData("resumeData", toStoreJson))

2024-04-17 00:16 UTC, yikai03 commented on backend/server.py
Done

2024-04-17 14:42 UTC, SHINE-six approved these changes

2024-04-17 14:42 UTC, merged